POST http://localhost:8080/events
Content-Type: application/json
Authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc0NDY0MzE2NiwidXNlcklkIjoyfQ.Sdfc_9Lxe9oSeueWno9-FKQtDm6Mfxpyp7gAy-jVf-s

{
	"name"      :  "test event new 3",
	"description" : "test description 3",
	"location"    : "test location 3",
	"dateTime"    : "2025-03-20T15:30:00Z"
}